// src/App.tsx
import React, { useState, useEffect } from "react";
import axios from "axios";
import TitleCard from "./components/TitleCard";
import Season from "./components/Season";
import { getSeasonIcon, calculateSeason } from "./utils/seasonCalculator";
import "./App.css";

const App: React.FC = () => {
  const [season, setSeason] = useState<number>(8);
  const [seasonState, setSeasonState] = useState(getSeasonIcon());

  useEffect(() => {
    const fetchWeather = async () => {
      try {
        const response = await axios.get(
          "https://api.openweathermap.org/data/2.5/weather",
          {
            params: {
              q: "Boston",
              appid: "a973c7588f25f457987274e21d050af1",
            },
          },
        );
        const tempMax = response.data.main.temp_max;
        const tempFahrenheit = ((tempMax - 273.15) * 9) / 5 + 32;
        setSeason(calculateSeason(tempFahrenheit));
      } catch (error) {
        console.error("Error fetching weather:", error);
      }
    };

    fetchWeather();
    const interval = setInterval(fetchWeather, 300000); // Update every 5 min
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    setSeasonState(getSeasonIcon());
    const interval = setInterval(() => setSeasonState(getSeasonIcon()), 60000); // Update every 1 min
    return () => clearInterval(interval);
  }, []);

  return (
    <div id="app">
      <TitleCard {...seasonState} />
      <Season season={season} />
    </div>
  );
};

export default App;

// src/App.vue
<template>
  <div id="app">
    <TitleCard v-bind="this.getSeasonIcon()" />
    <Season :season="this.getSeason()" />
  </div>
</template>

<script>
import TitleCard from './components/TitleCard.vue'
import Season from './components/Season.vue'
import $ from 'jquery'
import { getSeasonIcon, calculateSeason } from './utils/seasonCalculator'

function getWeather(q, callback) {
  const url = 'https://api.openweathermap.org/data/2.5/weather';
  const appid = "a973c7588f25f457987274e21d050af1"
  $.ajax({
    dataType: "jsonp",
    url: url,
    jsonCallback: 'jsonp',
    data: { q, appid },
    cache: false,
    success: function (data) {
      let {temp_max} = data.main;
      temp_max = (((temp_max - 273.15) * 9) / 5) + 32
      callback(temp_max);
    }
  });
}

function calcSeason(temp) {
  this.season = calculateSeason(temp)
}

function getSeason() {
  this.getWeather("Boston", this.calcSeason)
  return this.season
}

export default {
  name: 'App',
  components: {
    TitleCard,
    Season
  },
  methods: {
    getSeasonIcon,
    getSeason,
    calcSeason,
    getWeather
  },
  data: () => {
    return {
      season: 8
    }
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  margin-top: 60px;
}
</style>
